# Generated by Django 3.1 on 2021-01-19 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordpolicy',
            name='is_alpha_numeric',
        ),
        migrations.RemoveField(
            model_name='passwordpolicy',
            name='must_mixed',
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='max_consecutive_char',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='max_consecutive_char_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='min_different_char',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='min_lowercase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='min_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='min_special_char',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='min_uppercase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='warn_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='min_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='passwordpolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_policy', to=settings.AUTH_USER_MODEL),
        ),
    ]
