# Generated by Django 3.1 on 2021-01-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210119_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordpolicy',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
